- name: Listen for color change events
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: Rule - Print event information
      condition: event.meta.headers is defined
      action:
        run_workflow_template:
          name: "Unicorn/ColorUpdated"
          organization: Default
          job_args:
            extra_vars:
              unicorn_color_changed: "{{ event.payload.color }}"
