---
- name: Set Unicorn color
  hosts: localhost
  gather_facts: false
  vars:
    unicorn_api: http://malina4b.lan:5000
    __unicorn_color: "{{ unicorn_color_desired | default('keep') }}"
  tasks:
    - name: Set variable in Ansible automation controller inventory
      when: __unicorn_color != "keep"
      ansible.controller.inventory:
        state: present
        name: "Demo Inventory"
        organization: "Default"
        variables:
          unicorn_color: "{{ __unicorn_color }}"

    - name: Sync inventory
      when: __unicorn_color != "keep"
      ansible.builtin.set_fact:
        unicorn_color: "{{ __unicorn_color }}"

    - name: Unicorn Color updated
      ansible.builtin.debug:
        msg: "The color of the Unicorn is now: {{ unicorn_color }}"

    # - name: Call API
    #   ansible.builtin.uri:
    #     url: "{{ unicorn_api }}/unicorn/color"
    #     method: POST
    #     return_content: true
    #     status_code: 200
    #     body_format: json
    #     headers:
    #       Content-Type: application/json
    #     body: { "color": "{{ unicorn_color }}" }
    #   register: unicorn_response

    # - name: Print result from API Call
    #   ansible.builtin.debug:
    #     msg: "I've played unicorn and the response was: {{ unicorn_response }}"
