---
- name: Fix Color
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Print color
      ansible.builtin.debug:
        msg: "{{ unicorn_color }}"

    - name: Call API
      ansible.builtin.uri:
        url: "https://caap-automates-prague.cjung.ansible-labs.de/api/controller/v2/job_templates/Unicorn%2FFixColor++Default/launch/"
        method: POST
        user: admin
        password: "{{ controller_password }}"
        return_content: true
        status_code: 201
        body_format: json
        headers:
          Content-Type: application/json
      register: unicorn_response

    # - name: Print result from API Call
    #   ansible.builtin.debug:
    #     msg: "I've played unicorn and the response was: {{ unicorn_response }}"
