---
- name: Play music in Unicorn
  hosts: localhost
  gather_facts: false
  vars:
    unicorn_api: http://malina4b.lan:5000
  tasks:
    - name: Call API
      ansible.builtin.uri:
        url: "{{ unicorn_api }}/unicorn/audio"
        method: POST
        return_content: true
        status_code: 200
        body_format: json
        headers:
          Content-Type: application/json
        body: '{"audio_file": "AnsibleAutomates.mp3"}'
      register: unicorn_response

    - name: Print result from API Call
      ansible.builtin.debug:
        msg: "I've played unicorn and the response was: {{ unicorn_response }}"
